name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v2.1.4
    - name: Build
      run: |
        npm i
        ./build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build
        path: build

